stages:
  - build
  - update-helm

variables:
  IMAGE_NAME: gitlab.local:5050/root/kim-minji-frontend
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_HOST: unix:///var/run/docker.sock

build_and_push:
  stage: build
  tags:
    - arm64
    - docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD gitlab.local:5050
  script:
    - docker build --platform linux/arm64 -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:latest
  only:
    - develop
    - main

update_helm:
  stage: update-helm
  tags:
    - arm64
    - docker
  image: alpine:3.18
  before_script:
    - apk add --no-cache git wget
    - wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_arm64
    - chmod +x /usr/local/bin/yq
    - git config --global user.email "ci@gitlab.local"
    - git config --global user.name "GitLab CI"
  script:
    - git clone http://root:mj154415@gitlab.local/root/kim-minji-helm.git
    - cd kim-minji-helm
    - yq e '.image.tag = strenv(IMAGE_TAG)' -i frontend/values.yaml
    - git add frontend/values.yaml
    - git commit -m "ci update frontend image tag to ${CI_COMMIT_SHORT_SHA}"
    - git push origin main
  only:
    - main
